language: java
jdk:
- oraclejdk8
dist: trusty
install: true
script: mvn package -Ppublic -q
deploy:
  provider: script
  script: mvn deploy -DskipTests -Ppublic -s .travis.settings.xml
  skip_cleanup: true
env:
  global:
  - secure: PQavyKHMWhgZSsncD9C8RPnCeNACH6OljvWvZejCsH4k1L5hw1SJgNmD0sSI5pL0VzpNmWDFn+uymEakAlcKNwc/xwTuEtnFUzqzJ1dEFOl4456CO2bsgE0Xc6yodD7TQGF5QpOFMGLdMIQl1lz9muTI+zFp1AtXohd07r9/cXj48LP/xvYoBcbOpCeIw5WSChlCPyGCWp1KbltX6s5eQl9hQnT0GXYh8FjL9EhF+FYdna3PslSPaoyzFCYvS8RuRw6DzMDW3+9vEXDluOv9JY9uQ3jXWcW/PGxe/ptXbcVTOZRf0+U3b39JirWlyaMyxSGq4VXfDsjBkAibWpmKGzZ8TrEvdXkvEt00YaCvwxBkcU+S9Pbzq6RqKY34RUp9EeDQJFop+mNIyHqXqrnxaUTQ9+WFMiYC24hYqiHF8cGAolpEXLuOe+arO205xNu7bjRBji5ISdpkSaKBF7oUqEsYBIqjRxiuHC/1c1hpJd1bT5TvzY8AknzmOQUwj9k7ZdTQoWOM1rnrWK7qU5aJi1CFb1KhvCzH4AfwgakZpF4LJQQ96hG5aAdVSx9ItLIvp4nwcKY/+oH6UllqGz5YqVgMR7PT//IvAglVLpi0oeYeFByvgy1eIVJf+609X/fLEw1vYXE92Zx+P4elufkWdV1/tosF5hL8B8+0GxShQTM=
  - secure: K7gwCauqIWXaY+pVcuhdMxd5EccmO7cH7MrSgoHQL9Ak2+lde1oMX6uxj1awjD7MGE1xrcrjgcj+E0sM5ZeYYro1tn8D7glfnO8fZVCinbpM5HKS+INi+CdOYFgKKnu2fP4NrET+QBKjuq0f2w72CMMjGuUZdnqDYTr6CzlrDSxX75AahLwD4pvdxfWw/lytf415zeOIe3J9M/J5UA4za77ER4GbY3ldcAuHQvg14TofKnnd3o8XAV/Z97UaeuOK/RtW+VeuqDRg4iUT9ps+GYwjM6YTFGYRRybSc9sit8dV1ASkgPEM7UuHlFurJtIiWnAApg5AHm7B9cJinARqU723Qqa+gZ9cjfNknFhHnwn+dhLZK/7YWlNQItSLB8Im8ExRWDaZlOcjSuXVqUb/oH2B4/jcdJd1WmDC9oSlVlf4o2ImG0Xnj4amtxG6Ksp86DuchIv0cj+TRqqh+GJ+dZKtVYr1aQgi6PgRcUVZT0190cNAVH0S4WIlymXhHMkvMirHIOAe12nCeBhM1uNBDFcThchF1x/0Vsf15peIg2XXLQKkEh4DHilm5OxtGn1w1yFHvuytE5GMvqOkdMbpTNTou29OvRJaKIvbTo9oFXClJC/Vr4vEQmsJFLsPukx38/cqhCUnvt7hPS1N/zzVbSeMYFg9wJG7blFHY8G8Xe0=
